
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jul  7 2022 17:50:24 MSK (Jul  7 2022 14:50:24 UTC)

// Verification Directory fv/d_flip_flop 

module d_flip_flop(clk, d, q);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  DFFPOSX1 q_reg(.CLK (clk), .D (d), .Q (q));
endmodule

