
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jun 15 2022 18:55:48 MSK (Jun 15 2022 15:55:48 UTC)

// Verification Directory fv/half_adder 

module half_adder(x, y, z, carry_out);
  input x, y;
  output z, carry_out;
  wire x, y;
  wire z, carry_out;
  HAX1 g33(.A (y), .B (x), .YC (carry_out), .YS (z));
endmodule

